version: "3"

services:
  mysql:
    image: mysql:5.7.26
    container_name: swagger-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/scripts/init:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d

  api:
    build: .
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8081:8081"

volumes:
  db_data:
