/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"codegen/go/server"
	"log"
)

func main() {
	log.Printf("Server started")
	server.StartServer()
}
