/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

// Reservation type of reservations table
type Reservation struct {
	ID int64 `json:"id,omitempty"`

	ReservationDate time.Time `json:"reservationDate,omitempty"`

	ReservationTime time.Time `json:"reservationTime,omitempty"`

	ReservationType int8 `json:"reservationType,omitempty"`

	Purpose string `json:"purpose,omitempty"`

	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at" form:"updated_at"`

	CreatedAt time.Time `gorm:"column:created_at" json:"created_at" form:"created_at"`
}
