/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// User type of users table
type User struct {
	ID int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	Phone string `json:"phone,omitempty"`

	Prefecture string `json:"prefecture,omitempty"` // 都道府県

	City string `json:"city,omitempty"` // 市区町村

	Address1 string `json:"address1,omitempty"` // 町名

	Address2 string `json:"address2,omitempty"` // 番地

	Address3 string `json:"address3,omitempty"` // 建物名

	Zipcode string `json:"zipcode,omitempty"` // 郵便番号

	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at" form:"updated_at"`

	CreatedAt time.Time `gorm:"column:created_at" json:"created_at" form:"created_at"`
}
