/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type User struct {
	Id int64 `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`

	Phone string `json:"phone,omitempty"`

	// 都道府県
	Prefecture string `json:"prefecture,omitempty"`

	// 市区町村
	City string `json:"city,omitempty"`

	// 町名
	Address1 string `json:"address1,omitempty"`

	// 番地
	Address2 string `json:"address2,omitempty"`

	// 建物名
	Address3 string `json:"address3,omitempty"`

	// 郵便番号
	Zipcode string `json:"zipcode,omitempty"`
}
