/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UsersLogoutPost - logout user
func UsersLogoutPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersSigininPost - Login user
func UsersSigininPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersSiginupPost - Create a new User
func UsersSiginupPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersUpdatePut - update user
func UsersUpdatePut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
