/*
 * inazma-sample
 *
 * this api practice inazma
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ReservationsIdDelete - delete reservation
func ReservationsIdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReservationsIdGet - get reservation list
func ReservationsIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReservationsIdPut - update reservation
func ReservationsIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReservationsPost - create reservation
func ReservationsPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
